---
title: "Exercise 2"
author: "Peter S. Hovmand"
date: "1/26/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

There are a variety of ways to exchange and maintain RStudio project files on the HPC between your directory on the HPC, local computer, and project repository (e.g., on Box, Dropbox, Google Drive, GitHub). Among these, GitHub is a platform that has been specifically designed and used to support opensource software development project. GitHub is a distributed versioning system including an online database of projects (https://github.com/), desktop and command line or terminal tools. 

GitHub stores projects and versions of work in respository. A repository is an collection that can have multiple folders and files, multiple projects associated with a collection, and releases. GitHub supports cloning a respository (making a copy that synchronized with)

# Instructions

Step 1. In RStudio on the HPC through OnDemand, create folder where you want to store the cloned directory and set that as your current working directory. 

Step 2. in Rstudio Terminal, clone the respository SD R User Group repository using the following command, `git clone https://github.com/CBSDLab/SD-R-user-group.git`. 





